#!/bin/bash

# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script runs all tests and examples and verifies they work as expected.

info_message()    { echo -e "\033[0;33m$@\033[0m"; }
error_message()   { echo -e "\033[0;31m$@\033[0m"; }
success_message() { echo -e "\033[0;32m$@\033[0m"; }

tests_passed=0
tests_failed=0

for test_script in `find . -type f -name "test-*.sh"`; do
  example_name="$( basename "$test_script" | sed 's/.sh$//' )"
  info_message "Running $example_name"
  test_script_output="$( $test_script 2>&1 )"
  if [ $? -eq 0 ]; then
    success_message "Checks: OK"
    tests_passed=$(( tests_passed + 1 ))
  else
    error_message "Checks: ERROR (status: $?)"
    echo -e "$test_script_output"
    tests_failed=$(( tests_passed + 1 ))
  fi
done

echo
success_message "$tests_passed Tests passed"
if [ "$tests_failed" -gt 0 ]; then
  error_message "$tests_failed Tests failed"
  exit 1
fi
