#!/bin/bash
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Takes a version string and optional version message. Updates the version
# number in the files it is referenced in the source repo, commits the files,
# and tags that commit with that version string (prepended with a "v").
#
# There should be no uncommitted and unignored source files before running this command.

VER="$1"
MESSAGE="${2:-}"
if [ -z "${VER}" ] ; then
  echo Usage: tag_version VERSION [ MESSAGE ]
  exit 2
fi

STATUS_OUTPUT="$(git status -s)"
if [ -n "${STATUS_OUTPUT}" ] ; then
  echo -e "Uncommitted/unignored files in repository.\n${STATUS_OUTPUT}\n\nAborting tag_version."
  exit 1
fi

echo "Applying tag ${VER} ${MESSAGE}"
sed -i -E "s/VERSION = '([.0-9]+)'/VERSION = '${VER}'/" test_sample.py
sed -i -E "s/Version: ([.0-9]+)/Version: ${VER}/" README.md
git commit -m "Tagging ${VER}" -m "${MESSAGE}" test_sample.py README.md
git tag -a "v${VER}" -m "${MESSAGE}"

echo "Finished applying tag ${VER}"

