#!/bin/bash

# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit correctly depending on whether this file is being sourced or executed.
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && EXIT=return || EXIT=exit

pushd "$(dirname ${BASH_SOURCE})/.." >& /dev/null

python3 -m unittest discover --start-directory . --pattern '*_test.py' --verbose
code=$?

popd >& /dev/null
${EXIT} $code
