version: 2
jobs:
  build:
    working_directory: ~/sample-tester
    docker:
      - image: circleci/python:3.10.1
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pipenv install .
            . devcheck
