#!/bin/bash

# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit correctly depending on whether this file is being sourced or executed.
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && EXIT=return || EXIT=exit

pushd "$(dirname ${BASH_SOURCE})/../.." >& /dev/null

echo "Test sample-tester --xunit=file output"

xunit_file="$(mktemp /tmp/sample-tester.XXXXXXXXX )"

sample-tester --xunit="$xunit_file" --convention=tag:sample examples/convention-tag/language.test.yaml examples/convention-tag/language.manifest.yaml

xunit_xml="$( cat "$xunit_file" )"
code=0

for expected_text in                        \
  '<testsuite name="Language samples test'  \
  '<testcase name="A test defined via yaml'     \
  '<system-out>'                            \
  'In setup &quot;hi&quot;'                  \
  'Calling: python3 examples/mock-samples/' \
  'In teardown bye'                         \
;
do
  if ! grep --silent "$expected_text" "$xunit_file"; then
    echo "Assertion failed"
    echo "Expected $expected_text in:"
    echo "$xunit_xml"
    code=1
    break
  fi
done

popd >& /dev/null

if [[ $code -eq 0 ]] ; then
  echo "Tests passed"
fi
${EXIT} $code
